services:
    job_aggregator_app:
        container_name: job_aggregator
        build: .
        ports:
            - "8000:8000"
            - "3306:3306"
        volumes:
            - ${PROJECT_DIR}:/var/www/application
        post_start:
            - command: ["sh", "-c", "./init.sh"]
